### ISSUE TITLE
results are not consistent from xcor analysis

### ISSUE THREAD

**Issue by icanwinwyz** [ENCODE-DCC/chip-seq-pipeline2#57]
Hi,
Thanks for making this great pipeline!

I ran the pipeline three times with the same data but get the very different results from xcor analysis, especially on the value of RSC. 

I have two replicates for the ChIP samples. The first time I used the fastq files as input and got the RSC as 0.58 and 0.69, respectively, which indicated the low quality of libraries but I don't believe it at all since other QC metrics look good. The second time I used the bam removing the duplicates (nodup_bam gotten from the first time) as input and reran the xcor analysis in your pipeline and got the RSC as 1.08 and 1.07, which is expected.  Then, I ran the xcor analysis again and got the RSC around 1.08 for both samples. I know your pipeline integrated the Phantompeakqualtools for xcor analysis which uses the 15M randomly selected reads as input and the variation from the reads selection would affect the results. But I didn't expect the results were so inconsistent! It is possible that people would make wrong decision about the library quality. So what do you think about this issue? Is there any way to avoid this? Increase the number of reads as input? Many thanks.

BTW, I attached the figures generated from xcor analysis in case you would like to take a look.

[1st_sample2.pdf](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2891596/1st_sample2.pdf)
[1st_sample1.pdf](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2891597/1st_sample1.pdf)
[2nd_sample1.pdf](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2891598/2nd_sample1.pdf)
[2nd_sample2.pdf](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/2891599/2nd_sample2.pdf)

**Comment by leepc12** [comment]
This is an expected behavior. For the cross-correlation analysis (`xcor`), there is a special processing line for paired-ended samples. R1 FASTQ will be trimmed to 50bp and will be mapped as single-ended FASTQ to BAM. This BAM will be feed into phantompeakqualtools without filtering. But if the pipeline  starts from other types of inputs (BAM, FILT_BAM and TAG-ALIGN), it does not have R1 FASTQ so it tries to get the best output. Therefore, three cases will lead to different output for `xcor`.

1) Starting from FASTQ (R1 fastq will be trimmed to 50bp, mapped like SE, no filtering of BAM)
2) Starting from BAM (unfiltered PE BAM will be used for `xcor`)
3) Starting from NODUP BAM, TAG-ALIGN (filtered BAM and TA will be used for `xcor`)

We will add this to the documentation later.

**Comment by icanwinwyz** [comment]
Hi leepc12,
Thanks for your reply! It makes a lot of sense. I think no matter the input is (BAM or FASTQ), we will use the filtered BAM for downstream analysis. So my question is why not we use BAM for xcor in the pipeline regardless of format of input to avoid the inconsistency?

**Comment by icanwinwyz** [comment]
Hi leepc12,
I saw for the old version pipeline, you have a option that we can set "No fastq trimming and use PE tagAlign for cross-corr. (PE only)". Is this option available in this new version pipeline?

**Comment by leepc12** [comment]
@icanwinwyz : Okay, I will add that parameter (something like `use_pe_tagalign_for_xcor`) to the next release.

**Comment by akundaje** [comment]
@leepc12 @strattan This is a topic for further discussion on best way to design these parameters and consistency of results for different levels of input (FASTQ, BAM etc.). We want the choices to be as intuitive and consistent as possible. So we should discuss this in detail before adding a ton of alternate parameters which further muddles up exactly what is happening under the hood.

**Comment by akundaje** [comment]
@icanwinwyz The subsampling to 15M reads is important in order to keep the QC metrics calibrated across samples. Otherwise it is difficult to set reasonable cutoffs as sequencing depth affects quality.

Also, I would recommend not paying as much attention to RSC. The NSC, FRiP and the new Jensen-Shannon metrics are more stable and informative especially for datasets with reads > 50 bp.

**Comment by icanwinwyz** [comment]
Hi @leepc12 and @akundaje ,
Thanks for your help and explanation. I will keep that in mind.

**Comment by icanwinwyz** [comment]
I went through the website of phantompeakqualtools(https://code.google.com/archive/p/phantompeakqualtools/) for xcor analysis and they indeed mentioned that

"It is EXTREMELY important to filter out multi-mapping reads from the BAM/tagAlign files. Large number of multimapping reads can severly affect the phantom peak coefficient and peak calling results."

So I think it is better to use the filtered BAM as input for xcor analysis instead of raw FASTQ. Thanks.

Any comments?

**Comment by akundaje** [comment]
Sorry for the slow response. The exact procedure for the CC analysis in the pipeline is now as follows.

CC QC metrics are sensitive to SE/PE, read length and sequencing depth. We want to get QC metrics that are comparable across samples that are not confounded by the above mentioned parameters, so we do the following

1. For PE samples, we only use read1
2. Reads are then trimmed to 50 bp and mapped
3. Reads are filtered (-q 30 and -F 1804) which removed multimappers, unmapped, secondary alignments and other suboptimal aligned reads. However we keep duplicates since removing dups results in more attentuated metrics
4. Then we randomly subsample the mapped/filtered reads to 15M (This step can introduce some stochasticity in the CC values but is unavoidable in order to make metrics comparable and not sensitive to sequencing depth)
5. These are then fed into CC

There is an update to the pipeline incoming that stabilizes the CC code as mentioned above.
