### ISSUE TITLE
OSError: [Errno 1] Operation not permitted

### ISSUE THREAD

**Issue by dfarrell20** [ENCODE-DCC/chip-seq-pipeline2#63]
Running chip-seq-pipeline2 test fails with:
File "/beevol/home/paulk/.conda/envs/encode-chip-seq-pipeline/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
OSError: [Errno 1] Operation not permitted

Platform is Centos 7.5.1804
Cromwell-34.jar
Conda 4.3.30

[cromwell-executions.tar.gz](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3010420/cromwell-executions.tar.gz)

[stderr.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3010425/stderr.txt)

**Comment by leepc12** [comment]
Please try re-installing conda env for the pipeline.
```
$ conda/uninstall_dependencies.sh
$ conda/install_dependencies.sh
```

**Comment by dfarrell20** [comment]
I uninstalled and reinstalled but same error.

**Comment by leepc12** [comment]
Please try with Singularity instead of Conda.

**Comment by dfarrell20** [comment]
Ok, running singularity now.  Job is not crashing, however, it does not seem to progress beyond the point where it was failing before.  The java process is in sleep mode and the last output is [2019-03-29 08:26:16,77] [info] DispatchedConfigAsyncJobExecutionActor [ff345b11toy.trim:0:1]: Status change from - to WaitingForReturnCodeFile
[2019-03-29 08:26:16,78] [info] DispatchedConfigAsyncJobExecutionActor [ff345b11toy.trim:1:1]: Status change from - to WaitingForReturnCodeFile

Any ideas?  It has been running for ~1.5 hours

**Comment by dfarrell20** [comment]
Same error.  Output attached.
[encode_singularity_out.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3024069/encode_singularity_out.txt)

**Comment by dfarrell20** [comment]
Nevermind.  I found a work-around.

**Comment by xiaofanjin** [comment]
Hi, I'm not sure if this got fully resolved, but I encountered this exact problem and our hpc admin team believes this is due to encode_merge_fastq.py using a hardlink when there is only one file to merge. Our hpc cluster runs on a beegfs filesystem (appears to also be the case above), which doesn't allow hard-links between different directories. 

FWIW, I have successfully run the pipeline off a non-beeGFS filesystem

When I edit encode_merge_fastq.py to avoid using hard links even when 'merging' a single file, I am able to generate the expected fastq.gz files (/call-merge_fastq/shard-0/execution/R1/rep1-R1.subsampled.67.merged.fastq.gz), whereas I wasn't able to before. However, the pipeline still stalls with the following error

[error] WorkflowManagerActor Workflow f3c071d7-2d66-4047-b961-e6e9cfdaeec2 failed (during ExecutingWorkflowState): cromwell.backend.standard.StandardAsyncExecutionActor$$anon$2: Failed to evaluate job outputs:
Bad output 'merge_fastq_ctl.merged_fastq_R1': Failed to find index Success(WomInteger(0)) on array:
Success([])
0

It seems the merged fastq.gz is being created, but for some reason not found? 

[output.txt](https://github.com/ENCODE-DCC/chip-seq-pipeline2/files/3684063/output.txt)
