### ISSUE TITLE
resumer.py default template  is missing mandatory chip.pipeline_type argument. 

### ISSUE THREAD

**Issue by annashcherbina** [ENCODE-DCC/chip-seq-pipeline2#68]
output of resumer.py is mising "chip.pipeline_type", even though this argument is present in the original input.json file.

**Comment by leepc12** [comment]
The problem is in the `metadata.json file` generated from Cromwell.
`cromwell-34.jar` doesn't seem to store an original input JSON string (at `submittedFiles.inputs` correctly in a `metadata.json` generated for a failed workflow. Sometimes it has a weird trailing comma or missing variables defined in the original input JSON.

I will further look into this problem and let you know.

**Comment by XDtim** [comment]
Going to the latest release of Cromwell may help the problem.  Particularly in v37 and v36, issues with the metadata.json file were addressed.

**Comment by leepc12** [comment]
Resumer has been deprecated.
